Ref #3218 - Add the LGPL mySQL JDBC driver in studio distribution
Qualif error in trunk come from the unwanted commit of Elodie of the mysql-connector_fake.jar, that cause the !FakeJarException instead of using the true mysql connector from tomcat/lib.

Also add a java version checking before Driver switch to prevent the !NoClassDefFoundError on java.sql.NClob (and just let the !NoClassDefFoundError for com.mysql.jdbc.Driver).